### PR TITLE
add hello_world in PHP

### PR DESCRIPTION
**Pull request by riskodwis**
Hi, this is for hello_world in php

### CODE REVIEW

**Comment by almirpask** [comment]
@riskodwis I saw your `2022/riskodwis/hello_world.php` and it seems to be empty, can you put a hello world code just to follow the repository rules? thanks for the contribution 😄

**Comment by riskodwis** [comment]
Wait, My bad. I'm sorry i'll change it quickly

**Comment by riskodwis** [comment]
I already update hello_world.php

**Comment by almirpask** [comment]
@riskodwis  thanks!

**Pull request merged**
